import Link from 'next/link';
import { SchemaMarkup } from '@/components/seo/SchemaMarkup';
import { generateBreadcrumbSchema } from '@/lib/utils/seo';

type Section = { title: string; text: string; source: string; label: string };
export const REVIEWED_STATES: Record<string, { name: string; summary: string; sections: Section[] }> = {
  alabama: { name: 'Alabama', summary: 'For an Alabama household, start with your electricity provider. We did not identify a general statewide consumer EV purchase rebate in the reviewed federal directory; utility charging programs have their own service-area and account requirements.', sections: [
    { title: 'Alabama Power: nighttime charging discount', text: 'Alabama Power lists a 1.7155¢ per kWh discount during 9 p.m.–5 a.m. for qualifying residential customers who own or lease a plug-in vehicle. Enrollment depends on the applicable residential rate. This is a discount from the underlying energy charge, not the total electricity price. Check your rate and enrollment before estimating savings.', source: 'https://www.alabamapower.com/residential/save-money-and-energy/electric-vehicles/ev-rate-program.html', label: 'Alabama Power EV Night Charging Discount' },
    { title: 'Home charging equipment', text: 'Alabama Power also links a home charger rebate program. Confirm the eligible equipment, installation requirements, current funding and application deadline before ordering. A customer served by another utility should ask that provider directly; an Alabama address alone does not establish eligibility.', source: 'https://www.alabamapower.com/residential/save-money-and-energy/electric-vehicles.html', label: 'Alabama Power electric vehicle programs' },
    { title: 'Separate household support from infrastructure grants', text: 'The federal Alternative Fuels Data Center lists state and utility programs, including infrastructure and fleet opportunities. Those grants should not be counted as a rebate on a private vehicle purchase. Use the directory to identify programs for your applicant type and confirm terms with the administrator.', source: 'https://afdc.energy.gov/laws/all?state=AL', label: 'AFDC: Alabama laws and incentives' },
  ] },
  delaware: { name: 'Delaware', summary: 'Delaware’s Clean Vehicle Rebate Program changed for vehicles purchased or leased from May 1, 2026. Check the approved vehicle list and the current application rules before including a rebate in your budget.', sections: [
    { title: 'Current rebate amounts', text: 'DNREC lists $2,500 for an eligible new battery EV with base MSRP below $40,000 and $1,500 for the $40,000–$50,000 band. Eligible new plug-in hybrids can receive $1,000. For eligible used vehicles, the listed amounts are $2,500 for a battery EV and $1,000 for a plug-in hybrid. Apply within 90 days of purchase. Applications for purchases or leases before May 1, 2026 are no longer accepted.', source: 'https://dnrec.delaware.gov/climate-coastal-energy/clean-transportation/vehicle-rebates/', label: 'DNREC: current rebate amounts and timing' },
    { title: 'Eligibility is more than the dealer price', text: 'The administrator requires a listed vehicle, a licensed-dealer transaction and Delaware registration in the applicant’s name. Leases need at least 36 months. Its rules specify base MSRP below $50,000 for new vehicles and a Kelley Blue Book fair purchase price below $40,000 for used vehicles; used models must be within eight model years. Private sales do not qualify. At a price boundary, confirm eligibility with the administrator rather than assuming a negotiated discount qualifies the car.', source: 'https://driveelectricdelaware.org/eligibility-requirements', label: 'Program administrator: eligibility and application documents' },
    { title: 'Choose how to apply', text: 'Ask a participating dealer whether it can process the rebate at purchase. For a post-purchase application, the administrator describes state supplier registration and a Supplier ID requirement. Prepare your agreement, registration and accepted proof of residency. Confirm current availability before signing; our guide does not reserve funding.', source: 'https://driveelectricdelaware.org/eligibility-requirements', label: 'Application process and documentation' },
  ] },
  mississippi: { name: 'Mississippi', summary: 'Mississippi EV assistance depends heavily on the utility serving your home. We did not identify a general statewide consumer purchase rebate in the reviewed federal directory. Check utility programs separately from statewide infrastructure or fleet funding.', sections: [
    { title: 'Mississippi Power: vehicle and charging programs', text: 'Mississippi Power maintains an electric vehicle program page with rebate information and contact details. Ask the utility to confirm the currently applicable vehicle or charger rebate form, purchase-date window and funding before buying. Do not budget from an old downloadable rebate form without checking that it still applies to your transaction.', source: 'https://www.mississippipower.com/residential/products-and-services/electric-vehicles.html', label: 'Mississippi Power electric vehicle programs' },
    { title: 'Check your provider and rate', text: 'The Alternative Fuels Data Center lists residential time-of-use options for Entergy Mississippi and separate commercial and infrastructure programs. A charging-station incentive for a business is not automatically available for a home installation. Match the provider, residential account and installation address before comparing offers.', source: 'https://afdc.energy.gov/laws/all?state=MS', label: 'AFDC: Mississippi laws and incentives' },
    { title: 'Get an installation quote before selecting a charger', text: 'Ask an electrician to separate equipment, electrical work and permitting in the quote. Then ask your provider which costs qualify and whether approval is required before work begins. Compare the complete installation price with any confirmed rebate; charger hardware alone may be only part of the project.', source: 'https://www.mississippipower.com/residential/ways-to-save/rebates---incentives.html', label: 'Mississippi Power residential rebates' },
  ] },
};

export function ReviewedIncentives({ slug }: { slug: string }) {
  const state = REVIEWED_STATES[slug];
  return <article className="mx-auto max-w-4xl space-y-8 px-4 py-10 text-text-secondary">
    <SchemaMarkup schema={generateBreadcrumbSchema([{ name: 'Home', href: '/' }, { name: 'EV incentives', href: '/ev-incentives' }, { name: state.name, href: `/ev-incentives/${slug}` }])} />
    <header><p className="text-sm text-accent">Official sources reviewed October 6, 2026</p><h1 className="mt-2 text-3xl font-bold text-text-primary">{state.name} EV incentives and charging rebates</h1><p className="mt-4">{state.summary}</p></header>
    {state.sections.map(section => <section key={section.title} className="space-y-3 rounded-xl border border-border bg-bg-secondary p-5"><h2 className="text-xl font-semibold text-text-primary">{section.title}</h2><p>{section.text}</p><a href={section.source} className="inline-block text-accent underline">{section.label}</a></section>)}
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-text-primary">Federal vehicle credit: acquisition deadline has passed</h2><p>The IRS says federal new, used and commercial clean-vehicle credits are unavailable for vehicles acquired after September 30, 2025. An earlier qualifying acquisition with later delivery needs its own review under the IRS rules. Do not add an automatic $7,500 or $4,000 federal credit to a new purchase budget today.</p><a className="text-accent underline" href="https://www.irs.gov/clean-vehicle-tax-credits">IRS clean vehicle tax credit guidance</a></section>
    <section className="space-y-3"><h2 className="text-2xl font-semibold text-text-primary">Build a realistic purchase budget</h2><ol className="list-decimal space-y-3 pl-5"><li>Get the vehicle’s complete out-the-door price, including taxes and fees.</li><li>Confirm each program with its administrator and save the eligibility terms applicable to your transaction.</li><li>Separate an immediate dealer discount from a rebate paid after application approval.</li><li>For a lease, ask who receives each incentive and how it changes your written quote.</li><li>Estimate home charging with your actual electricity tariff and installation cost.</li></ol><p><Link href="/charging-cost-calculator" className="text-accent underline">Estimate charging costs</Link> · <Link href="/ev-incentives" className="text-accent underline">Other state incentive guides</Link></p></section>
  </article>;
}
